### ISSUE TITLE
An error is displayed when trying to save a new/edited recipe if the ratio fields were focused

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla-extensions/normandy-devtools#517] opened 2020-10-15 14:22 UTC
**[Affected versions]:**
- Firefox Nightly 83.0a1, Build ID 20201014214248

**[Affected Platforms]:**
- Windows 10

**[Prerequisites]:**
- Have VPN access to the staging environment.
- Have the NDT addon (version 2.1.1) installed on a new profile.

**[Steps to reproduce]:**
1. Open the Firefox profile from prerequisites and click the NDT button from the Browser Toolbar.
2. Switch to the `Stage` environment and click the `Create Recipe` button.
3. Select `branched addon study` or `multi-preference-experiment` from the `Action` dropdown.
4. Fill out the form with valid information and **IGNORE** the `ratio` fields.
5. Focus one of the `ratio` fields then click the `Save` button.
6. Add a comment and click the `Save` button again.

**[Expected results]:**
- The recipe is successfully created.

**[Actual results]:**
- `An Error Occurred: {"arguments":{"branches":{"0":{"ratio":"'1' is not of type 'integer'"},"1":{"ratio":"'1' is not of type 'integer'"}}},"status":400}` is displayed and the recipe is not saved.

**[Notes]:**
- The issue is also reproducible when editing a recipe.
- The issue is not reproducible if the `ratio` fields are NOT focused before saving.
- Attached a screen recording of the issue.
![error is thrown when saving if the ratio field was focused](https://user-images.githubusercontent.com/18304511/96140934-2aac7680-0f09-11eb-8040-0aa1d254be5b.gif)

**Comment by rehandalal** [comment] 2021-01-03 17:37
Wasn't able to reproduce this. Closing for now.

**Closed as completed by rehandalal** 2021-01-03 17:37 UTC
Labels: defect, [QA]:Normal issue, [QA]:Verified fixed

**Comment by Softvision-PatriciuPop** [comment] 2021-01-12 13:16
I have verified that the issue is no longer reproducible using the following [build](https://github.com/mozilla-extensions/normandy-devtools/runs/1659305385). Tested using Firefox Nightly 86.0a1, Build ID 20210111215143 on Windows 10 x64.
