### ISSUE TITLE
Missing arguments error when creating a heartbeat recipe

### ISSUE THREAD

**Issue by raymak** [mozilla-extensions/normandy-devtools#340] opened 2020-08-06 20:24 UTC
Steps to reproduce:

1. Create a recipe.
2. Set action to "show-heartbeat". 
3. Fill in the input fields.
4. Save. 

The form is missing an input filed for the learn more URL, and when saving the recipe, it gives the error that's presented in the attached screenshot. 
<img width="513" alt="Screen Shot 2020-08-06 at 11 58 56 AM" src="https://user-images.githubusercontent.com/7936670/89579119-100ea080-d7e8-11ea-8d5c-52f74f0184bf.png">

Version 2.0.3

**Comment by mythmon** [comment] 2020-08-06 20:29
Since it is subtle, I wanted to point out that in my testing there was some conflict between `surveyId` and `surveyID` (note the varying capitalization). I'm not sure which is right.

Also, I believe that v1.138.0 of Normandy will change the behavior of empty fields slightly, which would allow this recipe to be created but it would still be incorrect. It may be difficult to reproduce @raymak's results soon.

**Comment by RosanneScholl** [comment] 2020-08-07 01:24
This blocks Delivery Console from being decommissioned, because it means a correct Heartbeat recipe can't be created until this issue is fixed.

**Comment by tiftran** [comment] 2020-08-11 04:04
I believe https://github.com/mozilla-extensions/normandy-devtools/pull/279 should've have fixed this, but it wasn't part of the v2.03 release?

**Comment by mythmon** [comment] 2020-08-11 13:55
Ah, good catch. Lets get a new release out soon then, maybe with #277 too.

**Comment by mythmon** [comment] 2020-09-15 17:37
This should be fixed with the release of 2.1.1.

**Closed as completed** 2020-09-15 17:37 UTC
