### ISSUE TITLE
Several fields and buttons overlap each other if the Browser width is under 660px

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla-extensions/normandy-devtools#521] opened 2020-10-16 12:45 UTC
**[Affected versions]:**
- Firefox Nightly 83.0a1, Build ID 20201015215335

**[Affected Platforms]:**
- Windows 10

**[Prerequisites]:**
- Have VPN access to the staging environment.
- Have the NDT addon (version 2.1.1) installed on a new profile.

**[Steps to reproduce]:**
1. Open the Firefox profile from prerequisites and click the NDT button from the Browser Toolbar.
2. Switch to the `Stage` environment and click the `Create Recipe` button.
3. Resize the browser width to a value of 660px or under.
4. Observe the `Add` button next to the `Version` field as you are resizing.
5. Set the `Sampling Type` to `Bucket` or `Namespace`.
6. Focus the `Start`, `Count`, and `Total` fields from left to right and observe the behavior.

**[Expected results]:**
- Step 4: The button is visible during and after the resize is made.
- Step 6: The fields are selectable from the start (left-most part) of the field.

**[Actual results]:**
- Step 4: The button is hidden behind the `Version` field.
- Step 6: The fields are selectable only from the middle of the fields.

**[Notes]:**
- The issue is also reproducible for the `Namespace` field when using the namespace `Sampling Type`.
- Attached a screen recording of the issue.
![overlapped fields when browser it at 660px width](https://user-images.githubusercontent.com/18304511/96258873-5ee56d00-0fc5-11eb-9899-dc769fcb485f.gif)

**Comment by mythmon** [comment] 2020-10-16 17:18
The overlapping start/count/etc fields at least should have been fixed in #395, which hasn't been released yet.

Can you test this again using a dep-signed add-on from the main branch? You can get that by 

1. Go to [the list of commits](https://github.com/mozilla-extensions/normandy-devtools/commits/main)
2. Click on the latest green checkmark, representating a successful CI run
3. From the popup, choose "dep-signing-normandy-devtools" and click the details link
4. Click "View in Taskcluster"
5. Expand the list of artifacts on the right side
6. Download the XPI file listed.

Note that as this is not a production signed XPI, you will need to use a non-release version of Firefox (Nightly or Unbranded), and set the preference `xpinstall.signatures.dev-root` to true.

**Comment by SoftVision-CiprianMuresan** [comment] 2020-10-21 11:59
I've used [this build](https://github.com/mozilla-extensions/normandy-devtools/runs/1286168623) and the behavior (start/count/total for Bucket and Namespace, as well as the Add button) I pointed out in the initial report is no longer reproducible with this version.

I did however notice that under ~1580 width the Up/Down arrows from the same fields are outside the fields themselves. 

![image](https://user-images.githubusercontent.com/18304511/96715669-992b8180-13ac-11eb-9079-3769490b60c9.png)

@mythmon, is this tracked somewhere? If not, should we update this ticket to track this new behavior instead?

**Comment by rehandalal** [comment] 2021-01-03 16:56
This is fixed

**Closed as completed by rehandalal** 2021-01-03 16:56 UTC
Labels: defect, [QA]:Normal issue, [QA]:Verified fixed

**Comment by Softvision-PatriciuPop** [comment] 2021-01-12 12:57
I have verified that the issue is no longer reproducible using the following [build](https://github.com/mozilla-extensions/normandy-devtools/runs/1659305385). Tested using Firefox Nightly 86.0a1, Build ID 20210111215143 on Windows 10 x64.
